
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Generador;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int LINEA = 30;
  public static final int TIMES = 4;
  public static final int END_VAR = 12;
  public static final int MENOS = 29;
  public static final int CADENA = 32;
  public static final int PYC = 31;
  public static final int ARR = 15;
  public static final int IGUAL = 19;
  public static final int OP = 24;
  public static final int DECIMAL = 7;
  public static final int END_ARR = 17;
  public static final int CON = 9;
  public static final int PARDER = 25;
  public static final int COL = 10;
  public static final int AT = 16;
  public static final int LBRACKET = 18;
  public static final int ID = 26;
  public static final int RBRACKET = 20;
  public static final int PROGRAM = 13;
  public static final int TIPO = 23;
  public static final int COMMA = 21;
  public static final int EOF = 0;
  public static final int END_PROGRAM = 14;
  public static final int DIV = 5;
  public static final int ADD = 2;
  public static final int MINUS = 3;
  public static final int PRINT = 8;
  public static final int error = 1;
  public static final int DEST = 22;
  public static final int ENTERO = 6;
  public static final int FIN = 27;
  public static final int MAS = 28;
  public static final int VAR = 11;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "ADD",
  "MINUS",
  "TIMES",
  "DIV",
  "ENTERO",
  "DECIMAL",
  "PRINT",
  "CON",
  "COL",
  "VAR",
  "END_VAR",
  "PROGRAM",
  "END_PROGRAM",
  "ARR",
  "AT",
  "END_ARR",
  "LBRACKET",
  "IGUAL",
  "RBRACKET",
  "COMMA",
  "DEST",
  "TIPO",
  "OP",
  "PARDER",
  "ID",
  "FIN",
  "MAS",
  "MENOS",
  "LINEA",
  "PYC",
  "CADENA"
  };
}

